name: jar publish

on: pull_request
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Checkstyle with Maven
      run: mvn checkstyle:check
    - uses: lcollins/checkstyle-github-action@v2.0.0
      with:
        path: '**/checkstyle-result.xml'
        
    - name: PMD with Maven
      run: mvn pmd:pmd
    - uses: lcollins/pmd-github-action@v2.0.0
      with:
        path: '**/pmd.xml'
        
    - name: Spotbugs with Maven
      run: mvn -DskipTests verify spotbugs:spotbugs
    - uses: lcollins/spotbugs-github-action@v2.0.0
      with:
        path: '**/spotbugsXml.xml'
